gpu_id: "0"
start: 0
end: 10
jump_ckpts: 2
trn_batch_size: 1
val_batch_size: 1
tst_batch_size: 1000
model_train_batch_size: 512
data_budget: 260
select_subset_every: 1
per_class: False
numclasses: 50
num_epochs: 200
print_every: 1
save_every: 5
pretrained: True
frozen: False
arch: 'ResNet50'
config_base_dir: "/bigstor/zsarwar/Imagenet_2012_subsets/MT_DO_Splits/"
do_train_config: "df_train_DO_1_Imagenet_48_no-wolf-dog-animals.pkl"
pretrained_ckpt_directory: "/bigstor/zsarwar/spurious_classifiers/checkpoints/DO_1_Imagenet_48_no-wolf-dog-animals_gradmatch_684ff55ca02060ab5636cf635d1c984e/"
root_save_dir: "/bigstor/zsarwar/GradMatch"
