plot_dir: "/bigstor/zsarwar/GradMatch/Plots/ckpt_ratios"
plot_dir_metrics: "/bigstor/zsarwar/GradMatch/Plots/ckpt_metrics"
df_root: "/bigstor/zsarwar/Imagenet_2012_subsets/MT_DO_Splits/"
df_retrieve_config: "df_train_DO_2_Imagenet_48_no-wolf-dog-animals.pkl"
gradmatch_omp_root: "/bigstor/zsarwar/GradMatch"
gradmatch_omp_config: DO_2_Imagenet_48_no-wolf-dog-animals_gradmatch_budget-100_perclass-False_998a279aa5e0f1725090a2af352e1ab7
per_class: False
DO_type: "DO-2"