plot_dir: "/bigstor/zsarwar/GradMatch/Plots/ckpt_ratios"
plot_dir_metrics: "/bigstor/zsarwar/GradMatch/Plots/ckpt_metrics"
df_root: "/bigstor/zsarwar/Imagenet_2012_subsets/MT_DO_Splits/"
df_retrieve_config: "df_train_DO_5_Imagenet_48_no-wolf-dog-animals.pkl"
gradmatch_omp_root: "/bigstor/zsarwar/GradMatch"
gradmatch_omp_config: DO_5_Imagenet_48_no-wolf-dog-animals_gradmatch_budget-100_perclass-False_778a8258dedbf569adf54de60392966f
per_class: False
DO_type: "DO-5"