per_class_gradmatch: False
df_root: "/bigstor/zsarwar/Imagenet_2012_subsets/MT_DO_Splits/"
df_retrieve_config: "df_train_DO_1_Imagenet_48_no-wolf-dog-animals.pkl"
gradmatch_retrieved_path: "/bigstor/zsarwar/GradMatch"
gradmatch_retrieved_config: "DO_1_Imagenet_48_no-wolf-dog-animals_gradmatch_budget-150_perclass-False_5c78902906bfe70713f74cbb186ab22e"
gradmatch_retrieved_out_path: "/bigstor/zsarwar/GradMatch/GradMatch_Retrievals/"
tot_samples_per_class_needed: 40
extra_classes_possible: False
checkpoint_idx: 1